# Generated by Django 3.1.3 on 2020-11-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190514_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='', verbose_name='ファイル'),
        ),
    ]
