# Generated by Django 3.1.3 on 2020-11-15 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201115_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.TextField(unique=True, verbose_name='テキスト'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tag'),
        ),
    ]
