# Generated by Django 3.1.3 on 2020-11-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
